# Max-offline anonymity: block MSA/cloud/telemetry hosts, randomize Wi-Fi MAC, move NTP.
# Does not wipe MachineGuid / SMBIOS / TPM. Does not hide your IP (use Mullvad on Windows for that).
param(
    [string]$KitRoot = $(if ($PSScriptRoot) { Split-Path -Parent $PSScriptRoot } else { 'C:\X47' }),
    [switch]$Revert
)

. (Join-Path $KitRoot 'lib\X47Common.ps1')
$script:X47Root = $KitRoot
X47-RequireAdmin
X47-Log '=== 08 anonymity ==='

$hostsPath = Join-Path $env:SystemRoot 'System32\drivers\etc\hosts'
$markerStart = '# --- x47-anon ---'
$markerEnd = '# --- x47-anon-end ---'
$backup = Join-Path $KitRoot 'logs\hosts.bak'
$listFile = Join-Path $KitRoot 'assets\telemetry-hosts.txt'

function Get-X47HostNames {
    if (-not (Test-Path $listFile)) { throw "missing $listFile" }
    Get-Content $listFile | ForEach-Object {
        $line = $_.Trim()
        if (-not $line -or $line.StartsWith('#')) { return }
        $line.Split()[0]
    } | Where-Object { $_ } | Select-Object -Unique
}

function Remove-X47HostsBlock {
    param([string]$Text)
    $pattern = '(?s)\r?\n?' + [regex]::Escape($markerStart) + '.*?' + [regex]::Escape($markerEnd) + '\r?\n?'
    return [regex]::Replace($Text, $pattern, "`r`n")
}

if ($Revert) {
    if (Test-Path $backup) {
        Copy-Item $backup $hostsPath -Force
        X47-Log "hosts restored from $backup" 'OK'
    } else {
        $raw = Get-Content -Path $hostsPath -Raw -ErrorAction SilentlyContinue
        if ($raw) {
            Set-Content -Path $hostsPath -Value (Remove-X47HostsBlock $raw) -Encoding ASCII -NoNewline
            X47-Log 'x47-anon hosts block stripped' 'OK'
        }
    }
    Get-NetFirewallRule -Group 'X47-Anon' -ErrorAction SilentlyContinue | Remove-NetFirewallRule -ErrorAction SilentlyContinue
    X47-Log 'X47-Anon firewall rules removed' 'OK'
    return
}

# --- Microsoft account lock ---
# 3 = block Microsoft accounts (local only). If sk1tz is already MSA, switch to local in Settings first.
X47-SetReg -Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System' -Name NoConnectedUser -Value 3
X47-SetReg -Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System' -Name BlockUserFromShowingAccountDetailsOnSignin -Value 1
X47-SetReg -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\WorkplaceJoin' -Name BlockAADWorkplaceJoin -Value 1
X47-Log 'Microsoft accounts blocked (NoConnectedUser=3)' 'OK'

# OneDrive policy (in case the app comes back)
X47-SetReg -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\OneDrive' -Name DisableFileSyncNGSC -Value 1
X47-SetReg -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\OneDrive' -Name DisableFileSync -Value 1
X47-SetReg -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\OneDrive' -Name PreventNetworkTrafficPreWin8 -Value 1

# Cloud clipboard / cross-device / consumer
X47-SetReg -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\System' -Name AllowClipboardHistory -Value 0
X47-SetReg -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\System' -Name AllowCrossDeviceClipboard -Value 0
X47-SetReg -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\CloudContent' -Name DisableConsumerAccountStateContent -Value 1
X47-SetReg -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\CloudContent' -Name DisableCloudOptimizedContent -Value 1
X47-SetReg -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\SettingSync' -Name DisableSettingSync -Value 2
X47-SetReg -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\SettingSync' -Name DisableSettingSyncUserOverride -Value 1

# --- hosts merge ---
X47-EnsureLog
if (-not (Test-Path $backup)) {
    Copy-Item $hostsPath $backup -Force
    X47-Log "hosts backup → $backup"
}
$existing = Get-Content -Path $hostsPath -Raw -ErrorAction SilentlyContinue
if (-not $existing) { $existing = '' }
$stripped = Remove-X47HostsBlock $existing
$names = @(Get-X47HostNames)
$block = @(
    $markerStart
    '# Generated by X47 08-anonymity.ps1 — revert: .\modules\08-anonymity.ps1 -Revert'
    '# Windows Update hosts are intentionally omitted.'
)
foreach ($n in $names) { $block += "0.0.0.0 $n" }
$block += $markerEnd
$out = $stripped.TrimEnd() + "`r`n`r`n" + ($block -join "`r`n") + "`r`n"
Set-Content -Path $hostsPath -Value $out -Encoding ASCII -NoNewline
X47-Log ("hosts: $($names.Count) names blocked") 'OK'

# Outbound firewall group (best-effort; hosts is the reliable half)
Get-NetFirewallRule -Group 'X47-Anon' -ErrorAction SilentlyContinue | Remove-NetFirewallRule -ErrorAction SilentlyContinue
$resolved = 0
foreach ($n in $names) {
    try {
        $addrs = @([System.Net.Dns]::GetHostAddresses($n) | ForEach-Object { $_.IPAddressToString } | Select-Object -Unique)
        if (-not $addrs) { continue }
        New-NetFirewallRule -DisplayName "X47-Anon $n" -Group 'X47-Anon' -Direction Outbound -Action Block -RemoteAddress $addrs -ErrorAction Stop | Out-Null
        $resolved++
    } catch {
        # Expected for names we just pointed at 0.0.0.0
    }
}
X47-Log "firewall X47-Anon rules for $resolved resolved names (others rely on hosts)"

# Wi-Fi random hardware address
try {
    $wifi = Get-NetAdapter -Physical | Where-Object { $_.Status -eq 'Up' -and $_.MediaType -match '802.11|Native 802.11|Wireless' }
    if (-not $wifi) { $wifi = Get-NetAdapter | Where-Object { $_.InterfaceDescription -match 'Wi-?Fi|Wireless|802.11' } }
    foreach ($if in $wifi) {
        try {
            Set-NetAdapterAdvancedProperty -Name $if.Name -DisplayName 'Network Address' -DisplayValue 'Random' -ErrorAction SilentlyContinue
        } catch {}
        X47-SetReg -Path 'HKLM:\SOFTWARE\Microsoft\WcmSvc\TetheringManager' -Name TetheringEnabled -Value 0
    }
    # Win11 per-network random MAC (interface GUID)
    X47-SetReg -Path 'HKLM:\SOFTWARE\Microsoft\WlanSvc\AnqpCache' -Name OsuFailCount -Value 0
    netsh wlan set randomization enabled=yes 2>$null | Out-Null
    X47-Log 'Wi-Fi MAC randomization enabled (best-effort)' 'OK'
} catch {
    X47-Log "MAC randomization: $($_.Exception.Message)" 'WARN'
}

# NTP: Mullvad if present, else pool.ntp.org
$ntp = 'pool.ntp.org'
if (Get-Service -Name 'MullvadVPN' -ErrorAction SilentlyContinue) {
    $ntp = '193.138.218.74'  # Mullvad ntp if the app is installed
}
try {
    w32tm /config /syncfromflags:manual /manualpeerlist:"$ntp" /update | Out-Null
    Restart-Service w32time -ErrorAction SilentlyContinue
    X47-Log "NTP → $ntp" 'OK'
} catch {
    X47-Log "NTP change failed: $($_.Exception.Message)" 'WARN'
}

$revert = Join-Path $KitRoot 'logs\revert-anonymity.txt'
@"
Revert X47 anonymity (hosts + X47-Anon firewall):
  powershell -ExecutionPolicy Bypass -File C:\X47\modules\08-anonymity.ps1 -Revert

To allow Microsoft accounts again, set:
  HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\NoConnectedUser = 0
"@ | Set-Content $revert -Encoding UTF8

Write-Host ''
Write-Host 'If this Windows user is a Microsoft account: Settings → Accounts → Your info → Sign in with a local account instead.' -ForegroundColor Yellow
Write-Host 'Then sign in local-only. Store / OneDrive / Xbox Live / login.live.com are blocked.' -ForegroundColor Yellow
Write-Host "IP is still visible to your ISP unless Mullvad is running on Windows. Revert: $revert"
Write-Host ''
X47-Log 'anonymity pass finished' 'OK'
