[Icon Theme]
Name=Hicolor
Comment=Fallback icon theme
Directories=scalable/apps,48x48/apps,64x64/apps,128x128/apps,256x256/apps,512x512/apps
Hidden=true
Example=folder

[scalable/apps]
Size=48
Type=Scalable
MinSize=1
MaxSize=256
Context=Applications

[48x48/apps]
Size=48
Type=Fixed
Context=Applications

[64x64/apps]
Size=64
Type=Fixed
Context=Applications

[128x128/apps]
Size=128
Type=Fixed
Context=Applications

[256x256/apps]
Size=256
Type=Fixed
Context=Applications

[512x512/apps]
Size=512
Type=Fixed
Context=Applications
